"""POST /api/compliance/gap-analysis  — Compliance Gap Detection Agent.
POST /api/compliance/evidence-package  — Audit Evidence Package Generator.

⚠️  DISCLAIMER: This API is a decision-support tool only. The outputs are
NOT legal or regulatory advice. Real compliance audits must be conducted by
qualified compliance officers. See compliance_agent.py for full disclaimer.
"""

from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from app.core.compliance_agent import compliance_agent

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["compliance"])

DISCLAIMER = (
    "⚠ DISCLAIMER: This report is generated by an AI decision-support tool and is "
    "NOT a substitute for a formal compliance audit conducted by a qualified compliance "
    "officer. All gap findings are illustrative and non-exhaustive. Real audits must be "
    "conducted by certified professionals familiar with applicable Indian regulations."
)


# --------------------------------------------------------------------------- #
# Schemas
# --------------------------------------------------------------------------- #
class GapAnalysisRequest(BaseModel):
    query: str = Field(
        ...,
        description="Facility area name or equipment tag to analyse (e.g. 'CDU-1', 'P-101A').",
    )


class GapItemOut(BaseModel):
    regulation_id: str
    regulation: str
    clause: str
    requirement: str
    severity: str
    status: str          # covered | partial | gap
    evidence_docs: list[str]
    gap_explanation: str
    remediation: str


class GapAnalysisResponse(BaseModel):
    query: str
    facility_area: str
    total_requirements: int
    covered: int
    partial: int
    gaps: int
    items: list[GapItemOut]
    disclaimer: str


class EvidencePackageRequest(BaseModel):
    regulation_id: str = Field(..., description="Regulation ID from the reference set (e.g. 'OISD-154').")


class EvidenceDocOut(BaseModel):
    filename: str
    relevance: str


class EvidencePackageResponse(BaseModel):
    regulation_id: str
    regulation: str
    clause: str
    requirement: str
    evidence_documents: list[EvidenceDocOut]
    coverage_summary: str
    disclaimer: str


# --------------------------------------------------------------------------- #
# Endpoints
# --------------------------------------------------------------------------- #
@router.get("/compliance/health")
async def compliance_health() -> dict[str, object]:
    """Liveness probe for the compliance subsystem."""
    from app.core.compliance_agent import REGULATORY_REFERENCES
    return {
        "status": "ok",
        "agent": "Gemini Compliance Gap Detector v1",
        "regulation_count": len(REGULATORY_REFERENCES),
        "disclaimer": "Decision-support tool only. Not legal advice.",
    }


@router.post(
    "/compliance/gap-analysis",
    response_model=GapAnalysisResponse,
    status_code=status.HTTP_200_OK,
    summary="Run regulatory compliance gap analysis for a facility area or equipment tag",
)
async def run_gap_analysis(request: GapAnalysisRequest) -> GapAnalysisResponse:
    """Cross-reference the ingested document corpus against Indian regulatory requirements.

    Returns a traffic-light assessment (covered / partial / gap) for each
    regulatory clause, with plain-language explanations and remediation suggestions.

    ⚠ NOT legal advice — see disclaimer in response.
    """
    try:
        report = compliance_agent.run_gap_analysis(request.query)
        return GapAnalysisResponse(
            query=report.query,
            facility_area=report.facility_area,
            total_requirements=report.total_requirements,
            covered=report.covered,
            partial=report.partial,
            gaps=report.gaps,
            items=[
                GapItemOut(
                    regulation_id=i.regulation_id,
                    regulation=i.regulation,
                    clause=i.clause,
                    requirement=i.requirement,
                    severity=i.severity,
                    status=i.status,
                    evidence_docs=i.evidence_docs,
                    gap_explanation=i.gap_explanation,
                    remediation=i.remediation,
                )
                for i in report.items
            ],
            disclaimer=DISCLAIMER,
        )
    except Exception as exc:  # noqa: BLE001
        logger.exception("Unexpected error in gap analysis")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Gap analysis failed: {exc}",
        )


@router.post(
    "/compliance/evidence-package",
    response_model=EvidencePackageResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate an audit evidence package for a specific regulation",
)
async def build_evidence_package(request: EvidencePackageRequest) -> EvidencePackageResponse:
    """Pull all corpus documents and citations related to a single regulation.

    Returns a structured summary suitable for presentation to an auditor.

    ⚠ NOT legal advice — see disclaimer in response.
    """
    try:
        pkg = compliance_agent.build_evidence_package(request.regulation_id)
        return EvidencePackageResponse(
            regulation_id=pkg.regulation_id,
            regulation=pkg.regulation,
            clause=pkg.clause,
            requirement=pkg.requirement,
            evidence_documents=[
                EvidenceDocOut(filename=d["filename"], relevance=d["relevance"])
                for d in pkg.evidence_documents
            ],
            coverage_summary=pkg.coverage_summary,
            disclaimer=pkg.disclaimer,
        )
    except Exception as exc:  # noqa: BLE001
        logger.exception("Unexpected error building evidence package")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Evidence package generation failed: {exc}",
        )
